version: "3"
services:
  nginx:
    restart: on-failure:3
    image: nginx:1.15.3
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    - "/local1/git/blue_sky/config/static:/var/www/static"
    ports:
    - "9001:80"
    - "9002:81"
    depends_on:
    - blue_sky
  devdb2:
    restart: on-failure:3
    image: postgres:9.4.14
    volumes:
    - "./pg_data:/var/lib/postgresl/data"
    - "./initdb/initbluesky.sql:/docker-entrypoint-initdb.d/01_initbluesky.sql"
    expose:
    - "5432"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  message_queue:
    restart: on-failure:3
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=blue_sky_user
    - RABBITMQ_DEFAULT_PASS=blue_sky_user
    expose:
    - "5672"
    - "15672"
    ports:
    - "9008:5672"
    - "9000:15672"
  blue_sky:
    #image: alleninstitute/at_em_imaging_workflow:timf
    image: alleninstitute/blue_sky:circus
    environment:
    - PYTHONPATH=/blue_sky:/blue_sky_workflow_engine:/blue_sky_workflow_engine/circus
    - DJANGO_SETTINGS_MODULE=blue_sky.settings
    - BLUE_SKY_SETTINGS=/blue_sky/config/docker_blue_sky_settings.yml
    - BLUE_GREEN=blue
    command: bash -c "cd /blue_sky; /bin/bash entry.sh"
    expose:
    - "8000"
    - "5557"
    - "8888"
    depends_on:
    - devdb2
    - message_queue
    volumes:
    - "/local1/git/blue_sky/config/data:/data:shared"
    - "/allen:/allen:shared"
    - "/local1/git/blue_sky_workflow_engine:/blue_sky_workflow_engine"
    - "/local1/git/blue_sky:/blue_sky"
    - "/local1/git/blue_sky/config/static:/var/www/static"
