version: "3"
services:
  nginx:
    restart: on-failure:3
    image: nginx:1.15.3
    volumes:
    - "./nginx-sw.conf:/etc/nginx/nginx.conf:ro"
    - "/local1/git/blue_sky/config/static:/var/www/static"
    ports:
    - "9001:80"
    - "9002:81"
    depends_on:
    - blue_sky
    - stanbol
    - marmotta
  devdb2:
    restart: on-failure:3
    image: postgres:9.4.14
    volumes:
    - "./pg_data:/var/lib/postgresl/data"
    - "./initdb/initbluesky.sql:/docker-entrypoint-initdb.d/01_initbluesky.sql"
    - "./initdb/initmarmotta.sql:/docker-entrypoint-initdb.d/02_initmarmotta.sql"
    expose:
    - "5432"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  message_queue:
    restart: on-failure:3
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=blue_sky_user
    - RABBITMQ_DEFAULT_PASS=blue_sky_user
    expose:
    - "5672"
    - "15672"
    ports:
    - "9008:5672"
    - "9000:15672"
  blue_sky:
    #image: alleninstitute/at_em_imaging_workflow:timf
    image: alleninstitute/blue_sky_base
    user: blue_sky_user
    environment:
    - PYTHONPATH=/green:/source/blue_sky:/source/blue_sky_workflow_engine:/app_dirs
    - DJANGO_SETTINGS_MODULE=settings
    - BLUE_SKY_SETTINGS=/green/blue_sky_settings.yml
    - BLUE_GREEN=green
    command: bash -c "while :; do sleep 3600; done"
    expose:
    - "8000"
    - "5557"
    - "8888"
    #ports:
    #- "9999:9999"
    #- "8080:8080"
    depends_on:
    - devdb2
    - message_queue
    volumes:
    - "/local1/git/blue_sky/config/data:/data:shared"
    - "/allen:/allen:shared"
    - "/local1/conda_envs/0.121.0:/conda_envs"
    - "/local1/app_dirs:/app_dirs:ro"
    - "/local1/git/blue_sky_workflow_engine:/source/blue_sky_workflow_engine"
    - "/local1/git/blue_sky:/source/blue_sky"
    - "/local1/git/blue_sky/config/static:/var/www/static"
    - "/local1/git/blue_sky/config/logs:/var/www/logs"
  stanbol:
    image: alleninstitute/stanbol
    hostname: stanbol
    expose:
      - 8080
    ports:
      - 7070:8080
    volumes:
      - ./vocabulary:/data/vocabulary:shared
  stanbol_data:
    image: alleninstitute/stanbol
    command: echo "Data only container for the Apache Stanbol container."
    volumes:
      - /var/log/supervisord
      - ./vocabulary:/data/vocabulary:shared
  marmotta:
    image: apache/marmotta
    hostname: marmotta
    depends_on:
    - devdb2
    expose:
      - 8080
    ports:
      - 9090:8080
    environment:
      - DB_NAME=marmotta
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PG_VERSION=9.4
  mongodb:
    image: mongo
    hostname: mongodb
    expose:
      - 8080
      - 8081
      - 27017
      - 27018
      - 27019
    ports:
      - 8181:8080
  webprotege:
    image: skyplabs/webprotege
    hostname: webprotege
    expose:
      - 8080
    ports:
      - 8282:8080
    #volumes:
    #  #- ./webprotege:/srv/webprotege
    #  #- ./webprotege/webprotege.properties:/etc/webprotege/webprotege.properties
    depends_on:
     - mongodb
