executables:

    mock:
        name: 'Mock Executable'
        path: '/allen/aibs/pipeline/image_processing/volume_assembly/workflow_conf/staging_old/bin/mock_executable'
        remote_queue: 'pbs'
        pbs_queue: 'emconnectome'
        pbs_processor: 'nodes=1:ppn=1'
        pbs_walltime: 'walltime=0:10:00'

run_states:
    - "PENDING"
    - "QUEUED"
    - "RUNNING"
    - "FINISHED_EXECUTION"
    - "FAILED_EXECUTION"
    - "FAILED"
    - "SUCCESS"
    - "PROCESS_KILLED"

workflows:
    mock_workflow:
        ingest: "blue_sky.strategies.mock_ingest.MockIngest"

        states:
            - key: "ingest_mock"
              label: "Ingest Mock"
              class: "blue_sky.strategies.mock_ingest.MockIngest"
              enqueued_class: "blue_sky.models.observation.Observation"
              executable: "mock"

            - key: "mock_analyze"
              label: "Mock Analyze"
              class: "blue_sky.strategies.mock_analyze.MockAnalyze"
              enqueued_class: "blue_sky.models.observation.Observation"
              executable: "mock"

            - key: "group_assign"
              label: "Group Assignment"
              class: "blue_sky.strategies.mock_group_assignment.MockGroupAssignment"
              enqueued_class: "blue_sky.models.observation.Observation"
              executable: "mock"

            - key: "process_grouped"
              label: "Process Grouped Observations"
              class: "blue_sky.strategies.process_grouped_observations.ProcessGroupedObservations"
              enqueued_class: "blue_sky.models.observation.Observation"
              executable: "mock"

            - key: "complete_group"
              label: "Complete Group"
              class: "blue_sky.strategies.mock_complete_group.MockCompleteGroup"
              enqueued_class: "blue_sky.models.observation_group.ObservationGroup"
              executable: "mock"

        graph:
            - [ "ingest_mock", [ "mock_analyze" ] ]
            - [ "mock_analyze", [ "group_assign" ] ]
            - [ "group_assign", [ "process_grouped" ] ]
            - [ "process_grouped", [ "complete_group" ] ]
