# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(null=True)),
                ('object_state', django_fsm.FSMField(default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg1', models.IntegerField(null=True)),
                ('arg2', models.CharField(max_length=255, null=True)),
                ('arg3', models.CharField(max_length=255, null=True)),
                ('object_state', django_fsm.FSMField(default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True)),
                ('object_state', django_fsm.FSMField(default='INCOMPLETE', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='groups',
            field=models.ManyToManyField(related_name='observations', through='blue_sky.GroupAssignment', to='blue_sky.ObservationGroup'),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blue_sky.ObservationGroup'),
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blue_sky.Observation'),
        ),
    ]
