# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blue_sky', '0002_auto_20190717_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blue_sky.Calibration'),
        ),
    ]
